//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManPowerEntities : DbContext
    {
        public ManPowerEntities()
            : base("name=ManPowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminArticle> AdminArticles { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<Buy> Buys { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<CaseStatu> CaseStatus { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<GdsSubClass> GdsSubClasses { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<GoodsClass> GoodsClasses { get; set; }
        public virtual DbSet<ManPower> ManPowers { get; set; }
        public virtual DbSet<MC_Match> MC_Match { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberStage> MemberStages { get; set; }
        public virtual DbSet<MPClass> MPClasses { get; set; }
        public virtual DbSet<MPSCList> MPSCLists { get; set; }
        public virtual DbSet<MPSubClass> MPSubClasses { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
